all: sum sub div fact myshell

CC= gcc

sum: sum.c
	$(CC) -o $@ sum.c

sub: sub.c
	$(CC) -o $@ sub.c

div: div.c
	$(CC) -o $@ div.c

fact: fact.c
	$(CC) -o $@ fact.c

myshell: myshell.c
	$(CC) -o $@ myshell.c

